### ISSUE TITLE
Display system temperature as whole number instead of decimal number

### ISSUE THREAD

**Issue by PankajRPandey** [PankajRPandey/TemperatureTray#6]
The value of system temperature is returned as a float value as string.
Change it to integer value by casting.

**Comment by areddy01** [comment]
@PankajRPandey  , I would like to start if anyone isn't working on it. I'm very much like to help as I am beginner in contributing to open source and it would help me with learning. Thank you!

**Comment by PankajRPandey** [comment]
Hey @areddy01 
There's already a PR for this issue. Keep an eye on this repo as I'll be creating a couple of more good first issues soon.
